CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uuid VARCHAR(100) NOT NULL,
  email VARCHAR(24) NOT NULL,
  password VARCHAR(16) NOT NULL,
  nickname VARCHAR(8),
  is_vip BOOLEAN NOT NULL,
  avatar_url VARCHAR(120),
  create_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)