CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  token VARCHAR(800),
  phoneNumber VARCHAR(16) NOT NULL,
  password VARCHAR(800) NOT NULL,
  nickname VARCHAR(32) NOT NULL,
  isVip BOOLEAN DEFAULT FALSE,
  avatar VARCHAR(255),
  isLogin BOOLEAN DEFAULT FALSE,
  vipExpiration TIMESTAMP,
  createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)